
import Head from "next/head";
import {getSession,  signIn, } from "next-auth/react";

export async function getServerSideProps({req}) {
  const session = await getSession({req});

  if(session){
    return{
      redirect:{
        destination: '/teste',
        permanent: false
      }
    }
  }
  return {
    props: {}, // will be passed to the page component as props
  }
}


export default function Home() {
 

  function handleSignIn() {
    signIn("google");
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Sign In</h1>
      <button onClick={handleSignIn}>Sign in with Google</button>
     
    </div>
  );
}
