import Head from "next/head";

import { getSession, signIn } from "next-auth/react";

import { Container, EditGoogleButton, EditLinkedinButton, Sign } from "../styles/index";

export async function getServerSideProps({ req }) {
  const session = await getSession({ req });

  if (session) {
    return {
      redirect: {
        destination: "/app",
        permanent: false,
      },
    };
  }
  return {
    props: {}, // will be passed to the page component as props
  };
}

export default function Home() {
  function handleSignInGoogle() {
    signIn("google");
  }
  function handleSignInLinkedin() {
    signIn("linkedin");
  }
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sign>
        <h1>Welcome!</h1>
        <span>Sign in with your account to access our platform</span>
        <EditGoogleButton onClick={handleSignInGoogle}><span>Sign in with Google</span></EditGoogleButton>
        <EditLinkedinButton onClick={handleSignInLinkedin}><span>Sign in with Linkeding</span></EditLinkedinButton>
      </Sign>
    </Container>
  );
}
